accounts/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls.defaults import patterns, include, url
from accounts.views import ProfileView, ActivityListView, ActivityDetailView

urlpatterns = patterns('accounts.views',
                       url(r'^profile/$',
                           login_required(ProfileView.as_view()),
                           name='profile'
                           ),

                       url(r'^activity/$',
                           login_required(ActivityListView.as_view()),
                           name='activities'),

                       url(r'^activity/(?P<pk>\d+)$',
                           login_required(ActivityDetailView.as_view()),
                           name='activity-detail'),
                       )

urlpatterns += patterns('',
                       (r'^login/$', 'django.contrib.auth.views.login',
                        {'template_name': 'accounts/login.html'},
                        "login"
                        ),

                       (r'^logout/$', 'django.contrib.auth.views.logout',
                        {'template_name': 'accounts/logout.html'},
                        "logout",
                        ),

                       (r'^changepasswd/$', 'django.contrib.auth.views.password_change',
                        {'template_name': 'accounts/password_change_form.html'},
                        'change-passwd',
                        ),

                       (r'^changedone/$', 'django.contrib.auth.views.password_change_done',
                        {'template_name': 'accounts/password_change_done.html'},
                        ),
                        )

risksevaluation/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.csrf import csrf_exempt

from risksevaluation.views import RisksEvaluationDocumentDetailView
from risksevaluation.views import RisksEvaluationDocumentCreateView
from risksevaluation.views import RisksEvaluationDocumentUpdateView
from risksevaluation.views import RisksEvaluationDocumentDeleteView
from risksevaluation.views import RisksEvaluationDocumentListView
from risksevaluation.views import AllRisksEvaluationDocumentView
from risksevaluation.views import RiskFactorEvaluationView
from risksevaluation.views import EvalRiskFactorStatusView
from risksevaluation.views import EvalRiskFactorProbabilityView, EvalRiskFactorSeriousnessView
from risksevaluation.views import UntakeMeasureView, TakeMeasureView
# red stands for Risks Evaluation Document

urlpatterns = patterns('risksevaluation.views',
                       url(r'^$',
                           login_required(AllRisksEvaluationDocumentView.as_view()),
                           name='red'),

                       url(r'^company/(?P<company>\d+)$',
                           login_required(RisksEvaluationDocumentListView.as_view()),
                           name='red-list'),

                       url(r'^(?P<company>\d+)/revision/(?P<pk>\d+)/$',
                           login_required(RisksEvaluationDocumentDetailView.as_view()),
                           name = 'red-detail'),

                       url(r'^(?P<company>\d+)/create/$',
                           login_required(RisksEvaluationDocumentCreateView.as_view()),
                           name = 'red-create'
                           ),

                       url(r'^(?P<company>\d+)/edit/(?P<pk>\d+)/$',
                           login_required(RisksEvaluationDocumentUpdateView.as_view()),
                           name = 'red-edit'
                           ),

                       url(r'^(?P<company>\d+)/delete/(?P<pk>\d+)/$',
                           login_required(RisksEvaluationDocumentDeleteView.as_view()),
                           name = 'red-delete'
                           ),
                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/eval/(?P<riskfactor>\d+)/$',
                           login_required(RiskFactorEvaluationView.as_view()),
                           name = 'eval'),

                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/status$',
                           login_required(csrf_exempt(EvalRiskFactorStatusView.as_view())),
                           name = 'status'),

                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/probeval$',
                           login_required(csrf_exempt(EvalRiskFactorProbabilityView.as_view())),
                           name = 'eval-probability'),

                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/sereval$',
                           login_required(csrf_exempt(EvalRiskFactorSeriousnessView.as_view())),
                           name = 'eval-seriousness'),

                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/take$',
                           login_required(csrf_exempt(TakeMeasureView.as_view())),
                           name = 'take'),

                       url(r'^(?P<company>\d+)/revision/(?P<revision>\d+)/untake$',
                           login_required(csrf_exempt(UntakeMeasureView.as_view())),
                           name = 'untake'),
                       )

secuchecklist/urls.py
from django.conf.urls.defaults import patterns, include, url

# using django-autocomplete default view
from autocomplete.views import autocomplete
import customers.autocomplete_settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^customers/', include('customers.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^riskfactors/', include('riskfactors.urls')),
    url(r'^risksevaluation/', include('risksevaluation.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include(autocomplete.urls)),
)

risksevaluation/models.py
# encoding: utf-8

from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.
class RisksEvaluationDocument(models.Model):
    company = models.ForeignKey('customers.CustomerCompany')
    revision = models.PositiveSmallIntegerField(_('Revision'))
    revision_description = models.TextField(_('Revision description'))
    record_date = models.DateTimeField(_('Revision Date'), auto_now_add=True)

    record_by = models.ForeignKey('accounts.UserProfile',
                                  related_name='risksevaluationdocument_created',
                                  verbose_name=_('Recorded by'))
    lastupdate_by = models.ForeignKey('accounts.UserProfile',
                                      related_name='risksevaluationdocument_edited',
                                      verbose_name=_('Last update by'))

    rls_check = models.BooleanField(_('RLS check'))
    doctor_check = models.BooleanField(_('Doctor check'))
    companyowner_check = models.BooleanField(_('Company Owner check'))

    def __unicode__(self):
        return '(%s %s)' % (self.revision, self.record_date)

    class Meta:
        ordering = ['record_date']
        verbose_name = _('Risks Evaluation Document')
        verbose_name_plural = _('Risks Evaluation Documents')
        unique_together = ('company', 'record_date', 'revision')

probability = (
    (1, _('Low')),
    (2, _('Medium-Low')),
    (3, _('Medium-High')),
    (4, _('High'))
    )

seriousness = (
    (1, _('Small')),
    (2, _('Modest')),
    (3, _('Remarkable')),
    (4, _('Severe')),
    )

statuses = (
    (1, _('Not Checked')),
    (2, _('Checked')),
    (3, _('Suspended')),
    (4, _('Not applicable')),
    )

class RiskFactorEvaluation(models.Model):
    document = models.ForeignKey(RisksEvaluationDocument)
    risk_factor = models.ForeignKey('riskfactors.RiskFactor')

    record_by = models.ForeignKey('accounts.UserProfile',
                                  related_name='factorevaluations_created',
                                  verbose_name=_('Recorded by'))
    lastupdate_by = models.ForeignKey('accounts.UserProfile',
                                      related_name='factorevaluations_edited',
                                      verbose_name=_('Last update by'))
    record_date = models.DateTimeField(_('Recorded on'), auto_now_add=True)

    status = models.PositiveSmallIntegerField(_('Status'), choices=statuses)

    probability = models.PositiveSmallIntegerField(_('Probability'), choices=probability, blank=True, null=True)
    seriousness = models.PositiveSmallIntegerField(_('Seriousness'), choices=seriousness, blank=True, null=True)
    measure_taken = models.BooleanField(_('Measure Taken'))

    class Meta:
        ordering = ['record_date']
        verbose_name = _('Risk Factor Evaluation')
        verbose_name_plural = _('Risk Factor Evaluations')
        unique_together = ('document','risk_factor')

    def __unicode__(self):
        return '%s %s' % (self.risk_factor.description, _('Valued'))

risksevaluation/forms.py
from django import forms
from risksevaluation.models import RisksEvaluationDocument, RiskFactorEvaluation

class RisksEvaluationDocumentForm(forms.ModelForm):
    class Meta:
        model = RisksEvaluationDocument
        exclude = ('company', 'record_by', 'lastupdate_by', 'revision')

class RiskFactorEvaluationForm(forms.ModelForm):
    class Meta:
        model = RiskFactorEvaluation
        exclude = ('document', 'risk_factor', 'record_by', 'lastupdate_by')

risksevaluation/templates/risksevaluation/base-checklist.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Check Lists" %}{% endblock %}
{% block title2 %}{% trans "Check Lists" %}{% endblock %}

{% block extrascript %}
  $("#mainmenuacco").accordion("option", "active", 2);
{% endblock %}

{% block riskfactorsmenu %}
<h3><a href="#">{% trans "Check Lists" %}</a></h3>
<div>
  <ul class="menu">
    <li>
      <a href="{% url checklists %}">
        {% trans "Check Lists" %}
      </a>
    </li>
  </ul>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/base-risksevaluationdocument.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Risks Evaluation Documents" %}{% endblock %}
{% block title2 %}{% trans "Risks Evaluation Documents" %}{% endblock %}

{% block extrascript %}
  $("#mainmenuacco").accordion("option", "active", 2);
{% endblock %}

{% block riskfactorsmenu %}
<h3><a href="#">{% trans "Risks Evaluation Documents" %}</a></h3>
<div>
  <ul class="menu">
    <li>
      <a href="{% url red %}">
        {% trans "Risks Evaluation Documents" %}
      </a>
    </li>
  </ul>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/riskevaluation_create_form.html
{% load i18n %}
{% if riskfactor.question %}
  {% if riskfactor.notes %}
  <div id="dlg-notes" title="{% trans "Notes" %}">
    <p>{{ riskfactor.notes }}</p>
  </div>
  {% endif %}
  {% if riskfactor.suggestion_yes %}
  <div id="dlg-sugg-yes" title="{% trans "Suggestion Yes" %}">
    <p>{{ riskfactor.suggestion_yes }}</p>
  </div>
  {% endif %}
  {% if riskfactor.suggestion_no %}
  <div id="dlg-sugg-no" title="{% trans "Suggestion No" %}">
    <p>{{ riskfactor.suggestion_no }}</p>
  </div>
  {% endif %}
  <h1 class="ui-helper-reset ui-widget-header">
    {% trans "Risk Factor Evaluation" %}: <span>{{ riskfactor.description }}</span>
  </h1>
  <form id="riskevalform">
    {% csrf_token %}
    <div class="ui-helper-reset ui-widget-content">
      <div id="tabs">
        <ul>
          <li><a href="#tabs-1">{% trans "Question" %}</a></li>
          <li><a href="#tabs-2">{% trans "Evaluation" %}</a></li>
          <li><a href="#tabs-3">{% trans "Measure" %}</a><li>
        </ul>
        <div id="tabs-1">
          <p>{{ riskfactor.question }}</p>
          <div style="padding: 10px 4px">
            {% if riskfactor.notes %}
            <a id="show-notes" title="{% trans "Notes" %}"></a>
            {% endif %}
            {% if riskfactor.suggestion_yes %}
            <a id="show-sugg-yes" title="{% trans "Suggestion Yes" %}"></a>
            {% endif %}
            {% if riskfactor.suggestion_yes %}
            <a id="show-sugg-no" title="{% trans "Suggestion No" %}"></a>
            {% endif %}
          </div>
          <input type="hidden" name="revision" id="id_revision" value="{{ document.revision }}"\>
          <input type="hidden" name="riskfactor" id="id_riskfactor" value="{{ riskfactor.id }}"\>
          <label for="id_status">{{ form.status.label_tag }}</label>
          {{ form.status }}
          {% if form.status.errors %}
          <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
            {% for error in form.status.errors %}
            <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        <div id="tabs-2">
          <p>{% trans "Risk Evaluation" %}</p>
          <fieldset>
            <table>
              <tr id="{{ form.probability.html_name }}">
                <td>
                   {{ form.probability.label_tag }}
                </td>
                <td>
                  {{ form.probability }}
                </td>
                 {% if form.probability.errors %}
                <td class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
                  {% for error in field.errors %}
                  <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                  {{ error }}
                </td>
                {% endfor %}
                {% endif %}
              </tr>
              <tr id="{{ form.seriousness.html_name }}">
                <td>
                  {{ form.seriousness.label_tag }}
                </td>
                <td>
                  {{ form.seriousness }}
                </td>
                {% if form.seriousness.errors %}
                <td class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
                  {% for error in field.errors %}
                  <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                  {{ error }}
                </td>
                {% endfor %}
                {% endif %}
              </tr>
            </table>
          </fieldset>
        </div>
        <div id="tabs-3">
          <p>{{riskfactor.measure}}</p>
	  <label for="id_measure_taken">{{ form.measure_taken.label_tag }}</label>
          {{ form.measure_taken }}
          {% if form.measure_taken.errors %}
          <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
            {% for error in form.measure_taken.errors %}
            <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </form>
</div>
{% else %}
  <p>{% trans "No risk factor question found" %}</p>
  {% if riskfactor.notes %}
  <script>
    $(function() {
    $( "#dlg-info" ).dialog();
    });
  </script>
  <div id="dlg-info" title="{% trans "Notes" %}">
    <p>{{ riskfactor.notes }}</p>
  </div>
  {% endif %}
{% endif %}

risksevaluation/templates/risksevaluation/risksevaluationdocument_confirm_delete.html
{% extends "customers/base-company.html" %}
{% load i18n %}

{% block content %}
<div class="ui-helper-reset ui-widget">
  <h1 class="ui-helper-reset ui-widget-header">{% trans "Are you sure?" %}</h1>
  <div class="ui-helper-reset ui-widget-content">
    <p>
      {% trans "Do you really want to remove" %}
      {% Risks Evaluation Document %} <em>{{ red.title }}</em> {% trans "for company" %} <strong>{{ red.company }}</strong>?
    </p>
    <form action="" method="post">{% csrf_token %}
      <div>
        <input type="hidden" name="post" value="yes">
        <input type="submit" value="{% trans "Yes, I'm sure" %}">
      </div>
    </form>
  </div>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/risksevaluationdocument_create_form.html
{% extends "customers/base-company.html" %}
{% load i18n %}

{% block extra_head %}
{{ form.media }}
{% endblock %}

{% block title %}{% trans "Risks Evaluation Document create" %}{% endblock %}

{% block content %}
<div class="ui-helper-reset ui-widget">
  <h1 class="ui-helper-reset ui-widget-header">{% trans "Risks Evaluation Document create" %}</h1>
  <div class="ui-helper-reset ui-widget-content">
    <form action="{{ form.success_url }}" method="post">{% csrf_token %}
      <fieldset>
        <table>
          {% for field in form %}
          <tr id="{{ field.html_name }}">
            <td>
              {{ field.label_tag }}
            </td>
            <td>
              {{ field }}
            </td>
            {% if field.errors %}
            <td class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
              {% for error in field.errors %}
              <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
              {{ error }}
            </td>
            {% endfor %}
            {% endif %}
          </tr>
          {% endfor %}
          <tr>
            <td></td>
            <td><input type="submit" value="{% trans "Create" %}"/></td>
          </tr>
        </table>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/risksevaluationdocument_detail.html
{% extends "customers/base-company.html" %}

{% load i18n %}

{% block extra_head %}
<script type="text/javascript" charset="utf-8" src="/static/js/jquery.cookie.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jquery.form.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.checkbox.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.themes.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.xml.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.contextmenu.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.html.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.sort.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.ui.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.dnd.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.json.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.state.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/jstree.unique.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/riskevaluation.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/riskfactor.tree.js"></script>
{% endblock %}

{% block title %}{% trans "Risks Evaluation Documents" %}{% endblock %}
{% block title2 %}{% trans "Risks Evaluation Documents" %}{% endblock %}

{% block content-top %}
  <a title="{% trans "Edit Risks Evaluation Document" %}" class="ui-state-default ui-corner-all ui-icon ui-icon-pencil" href="{% url red-edit company.id red.id %}"></a>
{% endblock %}

{% block content %}
  <script type="text/javascript">
    $(document).ready( function () {
    buildevaldocument();
    } );
    jQuery(document).ajaxSend(function(event, xhr, settings) {
    if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
    xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
    }
    });
  </script>
<div class="ui-helper-reset ui-widget">
  <h1 class="ui-helper-reset ui-widget-header">{% trans "Risks Evaluation Document" %}: {{ red.title }}</h1>
  <div style="margin: 10px">
    <table class="detail">
      <tr class="even">
        <td class="fieldname">{% trans "Revision" %}</td>
        <td> {{ red.id }}</td>
      </tr>
      <tr class="odd">
        <td class="fieldname">{% trans "Company" %}</td>
        <td> {{ red.company }}</td>
      </tr>
      <tr class="even">
        <td class="fieldname">{% trans "Recorded on" %}</td>
        <td> {{ red.record_date }} </td>
      </tr>
      <tr class="odd">
        <td class="fieldname">{% trans "Revision description" %}</td>
        <td> {{ red.revision_description }}</td>
      </tr>
      <!-- <tr class="odd"> -->
      <!--   <td class="fieldname">{% trans "Suggestion Yes" %}</td> -->
      <!--   <td> {{ riskfactor.suggestion_yes }} </td> -->
      <!-- </tr> -->
      <!-- <tr class="even"> -->
      <!--   <td class="fieldname">{% trans "Suggestion No" %}</td> -->
      <!--   <td> {{ riskfactor.suggestion_no }} </td> -->
      <!-- </tr> -->
      <!-- <tr class="odd"> -->
      <!--   <td class="fieldname">{% trans "Notes" %}</td> -->
      <!--   <td> {{ riskfactor.notes }} </td> -->
      <!-- </tr> -->
      <!-- <tr class="even"> -->
      <!--   <td class="fieldname">{% trans "Link" %}</td> -->
      <!--   <td> {{ riskfactor.link }} </td> -->
      <!-- </tr> -->
      <!-- <tr class="odd"> -->
      <!--   <td class="fieldname">{% trans "Filename" %}</td> -->
      <!--   <td> {{ riskfactor.filename }} </td> -->
      <!-- </tr> -->
      <!-- <tr class="even"> -->
      <!--   <td class="fieldname">{% trans "Parent" %}</td> -->
      <!--   <td> -->
      <!--     {% if riskfactor.parent %} -->
      <!--     <a href="{% url riskfactor-detail riskfactor.parent.id %}">{{ riskfactor.parent }}</a> -->
      <!--     {% else %} -->
      <!--     <a href="{% url riskfactors %}">{% trans "Reds" %}</td> -->
      <!--     {% endif %} -->
      <!--   </td> -->
      <!-- </tr> -->
    </table>
  </div>
  <div id="riskfactorevaluation" class="ui-helper-reset ui-widget">
  </div>
  <div class="ui-helper-reset ui-widget">
    <h1 class="ui-helper-reset ui-widget-header">{% trans "Risks Factors" %}</h1>
    <div id="riskfactors" style="margin: 10px">
    </div>
  </div>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/risksevaluationdocument_list.html
{% extends "customers/base-company.html" %}
{% load i18n %}

{% block extra_head %}
<link href="/static/datatables/css/demo_table_jui.css" type="text/css" media="all" rel="stylesheet"/>
<script type="text/javascript" charset="utf-8" src="/static/datatables/js/jquery.dataTables.js"></script>
{% endblock %}

{% block title %}{% trans "Risks Evaluation Documents" %}: {{ company.firm }} {% endblock %}
{% block title2 %}{% trans "Risks Evaluation Documents" %}: {{ company.firm }} {% endblock %}

{% block content-top %}
{% endblock %}
{% block content %}
<script type="text/javascript">
    $(document).ready( function () {
                           $('#red').dataTable({
                                                     "bJQueryUI": true,
  "oLanguage": { "sUrl": "/static/dataTables.italian.txt" },
                                                     "aoColumns": [/* Revision */ null,
                                                         /* record_date */ null,
                                                         /* revision_description */ null,
                                                         /* record_by */ null,
                                                         /* rls_check */ null,
                                                         /* doctor_check */ null,
                                                         /* owner_check */ null,
                                                         /* Azioni */ { "bSearchable": false,
                                                                        "bVisible": true,
                                                                        "bSortable": false,
                                                                        "mDataProp": null,
                                                                      },
                                                     ],
                                                 }
                                                );
                       } );
</script>

<div class="ui-helper-reset ui-widget">
  <h1 class="ui-helper-reset ui-widget-header">{% trans "Risks Evaluation Documents" %}</h1>
  <div style="margin-top: 10px">
    <table id="red" class="display">
      <thead>
        <tr>
          <th>{% trans "Revision" %}</th>
          <th>{% trans "Record on" %}</th>
          <th>{% trans "Revision description" %}</th>
          <th>{% trans "Record by" %}</th>
          <th>{% trans "RLS check" %}</th>
          <th>{% trans "Doctor check" %}</th>
          <th>{% trans "Company Owner" %}</th>
          <th>{% trans "Actions" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for red in reds %}
        <tr>
          <td>
            <a href="{% url red-detail company.id red.id %}">{{ red.revision }}</a>
          </td>
          <td>
            {{ red.record_date }}
          </td>
          <td>
            {{ red.revision_description }}
          </td>
          <td>
            <a href="{% url profile %}">{{ red.record_by }}</a>
          </td>
          <td>
            {{ red.rls_check }}
          </td>
          <td>
            {{ red.doctor_check }}
          </td>
          <td>
            {{ red.companyowner_check }}
          </td>
          <td>
            <a title="{% trans "Edit" %}" class="ui-state-default ui-corner-all ui-icon ui-icon-pencil" href=" url red-edit company.id red.id ">
              <a title="{% trans "Delete" %}" class="ui-state-default ui-corner-all ui-icon ui-icon-trash" href="url red-delete company.id red.id"></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

risksevaluation/templates/risksevaluation/risksevaluationdocument_update_form.html
{% extends "customers/base-company.html" %}
{% load i18n %}

{% block extra_head %}
{{ form.media }}
{% endblock %}

{% block title %}{% trans "Risks Evaluation Document Edit" %}{% endblock %}

{% block content %}
<div class="ui-helper-reset ui-widget">
  <h1 class="ui-helper-reset ui-widget-header">{% trans "Risks Evaluation Document Edit" %}</h1>
  <div class="ui-helper-reset ui-widget-content">
    <form action="{{ form.success_url }}" method="post">{% csrf_token %}
      <fieldset>
	<table>
	  {% for field in form %}
	  <tr id="{{ field.html_name }}">
	    <td>
	      {{ field.label_tag }}
	    </td>
	    <td>
	      {{ field }}
	    </td>
	    {% if field.errors %}
	    <td class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
	      {% for error in field.errors %}
	      <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
	      {{ error }}
	    </td>
	    {% endfor %}
	    {% endif %}
	  </tr>
	  {% endfor %}
	  <tr>
	    <td></td>
	    <td><input type="submit" value="{% trans "Update" %}"/></td>
	  </tr>
	</table>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}